//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnoSetupTools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMain() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InnoSetupTools.ResourceMain", typeof(ResourceMain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to { Auto-generated function. Remove this tag to customize. }
        ///function ExecAndCaptureOutput(const Cmd, Params: string; var Output: string): Boolean;
        ///var
        ///  TempFile: string;
        ///  ResultCode: Integer;
        ///  Buffer: AnsiString;
        ///begin
        ///  Log(&apos;ExecAndCaptureOutput...&apos;);
        ///
        ///  TempFile := ExpandConstant(&apos;{tmp}\dotnet_output.txt&apos;);
        ///
        ///  Log(&apos; Preparing to call &apos; + Cmd + &apos; &apos; + Params + &apos; &gt; &quot;&apos; + TempFile + &apos;&quot; 2&gt;&amp;1&apos;);
        ///
        ///  if Exec(&apos;cmd.exe&apos;,
        ///    &apos;/c &apos; + Cmd + &apos; &apos; + Params + &apos; &gt; &quot;&apos; + TempFile + &apos;&quot; 2&gt;&amp;1&quot;&apos;,
        ///    &apos;&apos;,
        ///    SW [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string moduleExecAndCaptureOutput {
            get {
                return ResourceManager.GetString("moduleExecAndCaptureOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to { Auto-generated function. Remove this tag to customize. }
        ///function ExtractMajorVersionFromInstaller(const FileName: string): Integer;
        ///var
        ///  VersionStart, DotPos: Integer;
        ///  VersionStr: string;
        ///begin
        ///  Log(&apos;ExtractMajorVersionFromInstaller...&apos;);
        ///
        ///  {
        ///    Version begins at position 24 in patterns like:
        ///    windowsdesktop-runtime-6.0.36-win-x64.exe
        ///    windowsdesktop-runtime-10.0.2-win-x64.exe
        ///  }
        ///  VersionStart := 24;
        ///
        ///  { Find the first &apos;.&apos; after the version start }
        ///  DotPos := PosEx(&apos;.&apos;, Fi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string moduleExtractMajorVersionFromInstaller {
            get {
                return ResourceManager.GetString("moduleExtractMajorVersionFromInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to { Auto-generated function. Remove this tag to customize. }
        ///function GetLine(const S: string; LineNumber: Integer): string;
        ///var
        ///  I, Count: Integer;
        ///  StartPos: Integer;
        ///begin
        ///  Count := 1;
        ///  StartPos := 1;
        ///
        ///  for I := 1 to Length(S) do
        ///  begin
        ///    if S[I] = #10 then
        ///    begin
        ///      if Count = LineNumber then
        ///      begin
        ///        Result := Trim(Copy(S, StartPos, I - StartPos));
        ///        Exit;
        ///      end;
        ///
        ///      Count := Count + 1;
        ///      StartPos := I + 1;
        ///    end;
        ///  end;
        ///
        ///  if Count = Li [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string moduleGetLine {
            get {
                return ResourceManager.GetString("moduleGetLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to { Auto-generated function. Remove this tag to customize. }
        ///function GetLineCount(const S: string): Integer;
        ///var
        ///  I: Integer;
        ///begin
        ///  Result := 1;
        ///  for I := 1 to Length(S) do
        ///  begin
        ///    if S[I] = #10 then
        ///      Result := Result + 1;
        ///  end;
        ///end;.
        /// </summary>
        internal static string moduleGetLineCount {
            get {
                return ResourceManager.GetString("moduleGetLineCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to { Auto-generated function. Remove this tag to customize. }
        ///procedure InitializeWizard;
        ///begin
        ///  if NeedsDotNet then
        ///  begin
        ///    WizardForm.StatusLabel.Caption := &apos;Downloading .NET Runtime...&apos;;
        ///    idpDownloadFile(&apos;{RuntimeDownloadUrl}/{RuntimeVersion}/{RuntimeInstallerName}&apos;,ExpandConstant(&apos;{tmp}\\{RuntimeInstallerName}&apos;));
        ///  end;
        ///end;.
        /// </summary>
        internal static string moduleInitializeWizard {
            get {
                return ResourceManager.GetString("moduleInitializeWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to { Auto-generated function. Remove this tag to customize. }
        ///function IsDotnetRuntimeInstalled(MajorVersion: Integer): Boolean;
        ///var
        ///  Output, Line: string;
        ///  I: Integer;
        ///begin
        ///  Result := False;
        ///
        ///  Log(&apos;IsDotnetRuntimeInstalled...&apos;);
        ///
        ///  if not ExecAndCaptureOutput(&apos;dotnet&apos;, &apos;--list-runtimes&apos;, Output) then
        ///  begin
        ///    Log(&apos; Could not capture output from dotnet --list-runtimes&apos;);
        ///    Exit;
        ///  end;
        ///
        ///  I := 1;
        ///  while I &lt;= GetLineCount(Output) do
        ///  begin
        ///    Line := GetLine(Output, I);
        ///
        ///    Lo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string moduleIsDotnetRuntimeInstalled {
            get {
                return ResourceManager.GetString("moduleIsDotnetRuntimeInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to { Auto-generated function. Remove this tag to customize. }
        ///function NeedsDotNet(): Boolean;
        ///var
        ///  Major: Integer;
        ///begin
        ///  Log(&apos;NeedsDotNet...&apos;);
        ///
        ///  Major := ExtractMajorVersionFromInstaller(&apos;{RuntimeInstallerName}&apos;);
        ///  Log(Format(&apos; Major .NET Version: %d&apos;, [Major]));
        ///
        ///  if Major = 0 then
        ///  begin
        ///    Log(&apos;Error: Unable to determine .NET major version from installer name: {RuntimeInstallerName}&apos;);
        ///    Result := True;
        ///    Exit;
        ///  end;
        ///
        ///  Result := not IsDotnetRuntimeInstalled(Major);
        ///end;.
        /// </summary>
        internal static string moduleNeedsDotNet {
            get {
                return ResourceManager.GetString("moduleNeedsDotNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to { Auto-generated function. Remove this tag to customize. }
        ///function PosEx(const SubStr, S: string; Offset: Integer): Integer;
        ///var
        ///  I: Integer;
        ///begin
        ///  Result := 0;
        ///
        ///  if Offset &lt; 1 then
        ///    Offset := 1;
        ///
        ///  for I := Offset to (Length(S) - Length(SubStr) + 1) do
        ///  begin
        ///    if Copy(S, I, Length(SubStr)) = SubStr then
        ///    begin
        ///      Result := I;
        ///      Exit;
        ///    end;
        ///  end;
        ///end;.
        /// </summary>
        internal static string modulePosEx {
            get {
                return ResourceManager.GetString("modulePosEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify SignTool.exe path and filename or set your
        /// SIGNTOOLPATH environment variable to the path
        /// to the path where SIGNTOOL.EXE is located..
        /// </summary>
        internal static string msgSignToolNotFound {
            get {
                return ResourceManager.GetString("msgSignToolNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:\s*\{\s*Auto-{0,1}generated\s*function\.{0,1}\s*Remove\s*this\s*tag\s*to\s*customize\.{0,1}\s*\}).
        /// </summary>
        internal static string rxAutogeneratedTag {
            get {
                return ResourceManager.GetString("rxAutogeneratedTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:(?&lt;bool&gt;1|True|Yes|^OK|Up|Good|Fine)).
        /// </summary>
        internal static string rxBoolTrue {
            get {
                return ResourceManager.GetString("rxBoolTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:^\s*Filename\:\s*\&quot;\{tmp\}\\{dotnetInstallerFilename}\&quot;).
        /// </summary>
        internal static string rxDotNetRunFilename {
            get {
                return ResourceManager.GetString("rxDotNetRunFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:^\s*Filename\:\s*\&quot;\{tmp\}\\{dotnetInstallerFamily}).
        /// </summary>
        internal static string rxDotNetRunFilenameFamily {
            get {
                return ResourceManager.GetString("rxDotNetRunFilenameFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:^\s*Source\:\s*\&quot;\{\#SourcePath\}\\{dotnetInstallerFilename}\&quot;).
        /// </summary>
        internal static string rxDotNetRuntimeFilePresence {
            get {
                return ResourceManager.GetString("rxDotNetRuntimeFilePresence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:^\s*\[(?&lt;sectionName&gt;[^\]]+)\]\s*$).
        /// </summary>
        internal static string rxInnoSetupSectionName {
            get {
                return ResourceManager.GetString("rxInnoSetupSectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?m:^(?&lt;line&gt;[^\r\n]*)(\r{0,1}\n|$)).
        /// </summary>
        internal static string rxLine {
            get {
                return ResourceManager.GetString("rxLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:^\s*(?&lt;begin&gt;begin)\s*$).
        /// </summary>
        internal static string rxPascalBegin {
            get {
                return ResourceManager.GetString("rxPascalBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?i:^\s*(?&lt;end&gt;end)(?&lt;stopChar&gt;[\.\;]{0,1})\s*$).
        /// </summary>
        internal static string rxPascalEnd {
            get {
                return ResourceManager.GetString("rxPascalEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended functionality supporting InnoSetup..
        /// </summary>
        internal static string Syntax {
            get {
                return ResourceManager.GetString("Syntax", resourceCulture);
            }
        }
    }
}
